DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;


CREATE TABLE IF NOT EXISTS posts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	creation_date INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
	title TEXT NOT NULL,
	post_description TEXT NOT NULL,
	content TEXT NOT NULL,
	viewes INTEGER DEFAULT 0 
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL,
	passwrd TEXT NOT NULL,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL
)
